/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CVSS_Calculator;

import burp.BurpExtender;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author moein
 */
public class About extends javax.swing.JPanel {

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        aboutTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        licenseButton = new javax.swing.JToggleButton();
        licensePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        licensetextArea = new javax.swing.JTextArea();

        aboutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Version", "0.1"},
                {"Creator", "Moein Fatehi"},
                {"Email", "moein.fatehi@gmail.com"},
                {"Website", "moeinfatehi.ir"},
                {"Copyright", "© 2015-2016 Moein Fatehi"},
                {"License", " GNU GPLv3"}
            },
            new String [] {
                "Project", "Project_Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(aboutTable);

        jLabel9.setText("CVSS Calculator - a tool for calculating CVSS score of vulnerabilities");

        licenseButton.setText("License");
        licenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseButtonActionPerformed(evt);
            }
        });

        licensetextArea.setEditable(false);
        licensetextArea.setColumns(20);
        licensetextArea.setLineWrap(true);
        licensetextArea.setRows(5);
        licensetextArea.setText("{Extension_Name} is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.\n\n{Extension_Name} is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License along with {Extension_Name}.  If not, see http://www.gnu.org/licenses/.");
        licensetextArea.setWrapStyleWord(true);
        jScrollPane3.setViewportView(licensetextArea);

        javax.swing.GroupLayout licensePanelLayout = new javax.swing.GroupLayout(licensePanel);
        licensePanel.setLayout(licensePanelLayout);
        licensePanelLayout.setHorizontalGroup(
            licensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        licensePanelLayout.setVerticalGroup(
            licensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(132, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addComponent(licenseButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(licensePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(licenseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(licensePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void licenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseButtonActionPerformed
        licensePanel.setVisible(licenseButton.isSelected());
    }//GEN-LAST:event_licenseButtonActionPerformed

    private void initialize() {
        update_About_Tab();
        licensePanel.setVisible(false);
        licensetextArea.setText(licensetextArea.getText().replaceAll("\\{Extension_Name}", BurpExtender.getProjectName()));
    }
    
    private void update_About_Tab() {
        //set version
        aboutTable.setValueAt(BurpExtender.getVersion(), 0, 1);
        //set project name
        aboutTable.getTableHeader().getColumnModel().getColumn(1).setHeaderValue(BurpExtender.getProjectName());
        Calendar calendar = new GregorianCalendar();
        int year = calendar.get(Calendar.YEAR);
        aboutTable.setValueAt("© "+(year-1)+"-"+year+" Moein Fatehi", 4, 1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JTable aboutTable;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton licenseButton;
    private javax.swing.JPanel licensePanel;
    private javax.swing.JTextArea licensetextArea;
    // End of variables declaration//GEN-END:variables
}
