/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CVSS_Calculator;

import java.awt.Font;

/**
 *
 * @author fatehi
 */
public class mainPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form testPanel
     */
    public mainPanel() {
        initComponents();
        initialize();
    }
    
    
    private void initialize() {
        cvss2 cvss2_Panel = new cvss2();
        jTabbedPane1.addTab("CVSS v2", cvss2_Panel);
        cvss3 cvss3_Panel = new cvss3();
        jTabbedPane1.addTab("CVSS v3", cvss3_Panel);
        About about_Panel=new About();
        jTabbedPane1.addTab("About", about_Panel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public static java.awt.Font getFont_mainTitle(){
        if(System.getProperty("os.name").equals("Linux")){
            return new java.awt.Font("URW Gothic L", 1, 14);
        }
        else{
             return new java.awt.Font("Comic Sans MS", Font.BOLD, 14);
        }
        
    }
    
    public static java.awt.Font getFont_secondTitle(){
        if(System.getProperty("os.name").equals("Linux")){
            return new java.awt.Font("URW Gothic L", 0, 12);
        }
        else{
             return new java.awt.Font("Comic Sans MS", 0, 12);
        }
    }
    
    public static java.awt.Font getFont_secondTitleBold(){
        if(System.getProperty("os.name").equals("Linux")){
            return new java.awt.Font("URW Gothic L", 1, 12);
        }
        else{
             return new java.awt.Font("Comic Sans MS", 1, 12);
        }
    }
    
    public static java.awt.Font getFont_table(){
        if(System.getProperty("os.name").equals("Linux")){
            return new java.awt.Font("URW Gothic L", 1, 13);
        }
        else{
             return new java.awt.Font("Comic Sans MS", 1, 13);
        }
    }
    public static java.awt.Font getFont_vector(){
        if(System.getProperty("os.name").equals("Linux")){
            return new java.awt.Font("URW Gothic L", 0, 10);
        }
        else{
             return new java.awt.Font("Comic Sans MS", 0, 10);
        }
    }

 }
